services:
  marky_app:
    build:
      context: app
      dockerfile: ../Dockerfile
    container_name: marky_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    expose:
      - 9000
    networks:
      - marky_network

  http:
    image: nginx:1.27.3
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    env_file:
      - .env
    depends_on:
      - marky_app
    networks:
      - marky_network
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: marky_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - marky_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - marky_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - marky_network

networks:
  marky_network:
    driver: bridge
